sudo: false
os:
- linux
language: node_js
node_js:
- '10'
install:
- npm i npminstall && npminstall
env:
  global:
  - secure: xHeI60d07Hj0tWMitWTaZ+eQPT17fM/x0AzirXn7bT0Tqoen0qsaLbZoz9nvEf71YjvhmTiFbBFyfVbFP+r+ZP69GvPpIik7AP3ri55vqGZpsxdipsyUPxEA7c7PsxuFXDw6VHG3cYWXD4EsUMUOFglgKp84p8BRCXHZE3n7U0jynl2BDkbSCjDwOOgYh3WzvCnxYApW/dok3KJni6E1uuFlRgLwzZx0H9wSQXM7mRectMLL3MsMiMebLVCbBhTaulSkcU0K4cUy/bG+o8b44uLGoL3w6aQbs2H6zjVX3rqBjMyMWc19vE/cCGcbNR6FEidejdti91ExtmTKXvFsMrFreM5sErojfTOmpLub+iQ7TPHpO19LiRcgwHs208YYs3zldeZURGgtilG9v/qutJeZumFkv3LBMojhT2qHzQptA1VCLylLpdyRXoVmHLBvWXZwbVVl23Uq274ODdKamy05jEWmhrPe+PGzaV16etH3WAsh4YGWcAjetvDhoN8c1X3T4yezWu+UwGZyAMn/1H6/vWdWedUAboWiP9v9xqq+m2+safUjBcOh6e2yhi6v+OHs8Mv3YpAilLvDaURLRwGcJzzc0kTkcf+UXFOsHQQZNa3dgIbN5l+7AGndhK2a2WVSt1fr4HU9uOq8WdYa1Z9X8gHSIlzh4aseJMKAAjo=
  - secure: XLgDwJWyby5s5pty986dDHdI3hLO0++NiEp6tNxxxyhf5jO+zYn9MZW8eOgZMk4cm/DzWZyurp128LogLqbY3pbpl6p9RMU4jtvJ3uM7cl6GZE63qRHRzlSpxTeO43xPY//q1BYMaundCC7IrwjrLNxKUiQ73Fhp4m+tDBQAcZapz3X733QspuksDlQufvDLj0ZZbUzywcamTKNm19ncSQRtrwtlga2Fu0mJE172vumVuFLs+5uEJzBHnqDWC1rIOUxnvjiw6IMbi61/2eZV1X5CK5IHdzqqUHmm56uhtOJMgtIMGeNSEIEas1PW/BmXn80hvwv8kZK40FxsfO9nDV9edsUCjeY6kZA7hBPQSKCuTz4SoAZdAfI6uoihA4rwHt5HiJef7ydVf8OHw5PQcXuBzc7lNelK9qyt9MJN5+2tKj2s/LaxTE8jeCpa1pAE2UAcio7VT0V0TQpEC8v6rAO3qHBsNyGOygfeGG0nSg/y8GkQYQt0z1y7YqjShpXgXcZZkmORN2fd+14B14t3qF0tCxtASWgC5h34BEVHH8vBRX1j5XNCLDE9FuGOrQlAamdbBmfOwF+0lJ0ZjXk9mOVXXQlfLQXfXyE6oqGZgrg0nn795NbovFc3ztAMvEcIrYovThlr2NyQltB0SuBNszKPpZK/fdjq7Z9UA4rn5TU=
script: npm run ci
after_script:
- npminstall codecov && codecov
